name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      NON_SENSITIVE_VARIABLE: some_value

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x # Replace with your desired .NET version

      - name: Restore dependencies and build
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: Use Environment Variable
        run: echo "Non-sensitive variable: $NON_SENSITIVE_VARIABLE"

      - name: Use Secret
        run: echo "This is a secret: ${{ secrets.API_KEY }}"

      - name: Create and Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: bin/Release
