name: CI/CD Workflow

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x # Replace with your desired .NET version

    - name: Restore dependencies and build
      working-directory: Users\anus1\source\repos\Test3\Test3>
      run: |
        dotnet restore
        dotnet build --configuration Release

    # Add more steps for testing, deployment, etc.
